### ISSUE TITLE
Addition of audio

### ISSUE THREAD

**Issue by 54nd339** [faahim/happy-birthday#15]
Can you please advice how to add an audio..

**Comment by faahim** [comment]
Hello @54nd339,

Thanks for checking out the project!

Audio can be added to the project by using the native HTML `<audio>` tag.
It looks like this:
```
<audio autoplay>
  <source src="path/to/audio.ogg" type="audio/ogg">
  <source src="path/to/audio.mp3" type="audio/mpeg">
  Your browser does not support the audio element.
</audio>
```

Adding it anywhere in the [index.html](https://github.com/faahim/happy-birthday/blob/master/index.html) file should work. If you wish to learn more about the audio tag, you can take a look at the [documentation here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio).

Hope this helps! Please feel free to ask any question you might have.
Have fun! 🙂

**Comment by xEpic0821** [comment]
@54nd339 Did you succeed in adding audio?? I am trying to add audio and autoplay it after opening site. I have added audio tag in html but audio isn't playing. Can you help me?
