### ISSUE TITLE
upload picture

### ISSUE THREAD

**Issue by Eddiewjy** [faahim/happy-birthday#205]
I uploaded my own picture, and change the json file, but the png doesn't show on page.
![9bb68092e13240120da809c7ff8f27e](https://github.com/user-attachments/assets/e1a1e439-5c0b-4e81-8dca-b3a801f092cb)

**Comment by Rabehmekkiou** [comment]
![Uploading 1734259044448.jpg…]()

**Comment by Rabehmekkiou** [comment]
Happy birthday to my 20 years
