### ISSUE TITLE
Customizeable 

### ISSUE THREAD

**Issue by TRC1337** [faahim/happy-birthday#41]
Pls, change all text lines from the index.html to the customize.json.
Because for using in other languages it's needed to edit the index.html to

**Comment by faahim** [comment]
Hi @TRC1337 

Thanks for checking out the project!

Yes, I realise that extended customisation requires users to know how to edit HTML and I would like to change that. I don't currently have a lot of time to dedicate to this project. But now that we've identified this as important, this will be the first thing I'll work on when I can manage some time.

Alternatively, if you're a programmer and want to contribute, please feel free to submit a PR - I'd be more than happy to accept any contribution.

Thanks!

**Comment by faahim** [comment]
Hello @TRC1337 

Happy to let you know, I've upgraded the project to support customization for all content via the JSON file, so editing HTML is no longer required (#47). Thanks again for creating the issue.

I'm gonna close this issue now, but feel free to let me know I can help with anything. :)
