### ISSUE TITLE
Audio autoplay

### ISSUE THREAD

**Issue by nad-if** [faahim/happy-birthday#5]
How to make audio play auto in this repository?

**Comment by faahim** [comment]
Hey @nad-if 👋 

I believe you'd have to use the HTML `<audio>` element for that. It accepts an attribute `autoplay` that makes the audio play automatically. See more details here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio

However, this isn't related to this project, so I'll close this issue. But feel free let me know if you need any help! 🙂
