### ISSUE TITLE
run-script-os: not found

### ISSUE THREAD

**Issue by crysosancher** [faahim/happy-birthday#85]
how to start it locally?

**Comment by zbennett** [comment]
It is just html and javascript so if you are running in vscode, download Live Server extension and hit Go Live. It will serve the website up on a local port.

**Comment by faahim** [comment]
Hi @crysosancher 

I hope you've got around it by now 😅 

But what @zbennett suggested should work perfectly fine (thanks a lot @zbennett!). If you're not using VSCode, or don't want to go that route, you also run `yarn` and `yarn start` from your command line to open up the dev server.

Going to close this issue, but please feel free to reopen it if you have any queries. 🙂
