### ISSUE TITLE
pls answer me :)

### ISSUE THREAD

**Issue by smallwhiteqwp** [faahim/happy-birthday#94]
How to change the position of the hat.svg?

**Comment by faahim** [comment]
Hello @smallwhiteqwp,

Thanks for checking out the project. The position of the hat can be changed through CSS styles. The relevant code is [here](https://github.com/faahim/happy-birthday/blob/master/style/style.css#L125). You also have to update the values for different screen sizes if you want to make it responsive.

Best of luck!
